volumes:
  fashion-data:
services:
  # react:
  #   image: node:lts-bullseye
  #   command: /bin/bash run.sh
  #   working_dir: /app
  #   volumes:
  #     - ./ghi/app:/app
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     HOST_OS: ${OS}
  #     NODE_ENV: development
  #     HOST: "0.0.0.0"
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=fashion-data
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - fashion-data:/var/lib/postgresql/data
  fashion:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8100:8000"
    volumes:
      - ./:/app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/fashion-data
      WAIT_HOSTS: postgres:5432
      WAIT_TIMEOUT: 240
