# Generated by Django 4.2.6 on 2023-10-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
