# Generated by Django 4.2.6 on 2023-10-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashions', '0002_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
